### ISSUE TITLE
Failed to activate the atom-react-native-style package

### ISSUE THREAD

**Issue by chaitu111** [yomybaby/atom-react-native-style#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-react-native-style](https://github.com/yomybaby/atom-react-native-style) package 0.2.0

### Stack Trace

Failed to activate the atom-react-native-style package

```
At Cannot find module './rn-style-provider'

Error: Cannot find module './rn-style-provider'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-react-native-style/lib/main.js:3:24)
    at /packages/atom-react-native-style/lib/main.js:25:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.30.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:220:40)
    at measure (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.30.0/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.30.0/resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-react-native-style 0.2.0 
```

**Comment by filipef101** [comment]
bump
